"""cl  migration

Revision ID: 992755d9d5fd
Revises: f2587d9cabb8
Create Date: 2025-05-28 00:10:01.344454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '992755d9d5fd'
down_revision = 'f2587d9cabb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('clients')
    op.drop_table('demo_business_analyses')
    op.drop_table('projects')
    op.drop_table('documents')
    op.drop_table('kanban_tickets')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('features')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sqlite.JSON(), nullable=True))

    op.create_table('kanban_tickets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=512), nullable=False),
    sa.Column('filetype', sa.VARCHAR(length=50), nullable=True),
    sa.Column('filesize', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('business_objective', sa.TEXT(), nullable=True),
    sa.Column('expected_deliverables', sqlite.JSON(), nullable=True),
    sa.Column('subscription_plan', sa.VARCHAR(length=100), nullable=True),
    sa.Column('target_audience', sqlite.JSON(), nullable=True),
    sa.Column('data_sources', sqlite.JSON(), nullable=True),
    sa.Column('data_volume', sa.VARCHAR(length=50), nullable=True),
    sa.Column('api_details', sqlite.JSON(), nullable=True),
    sa.Column('google_spreadsheet', sa.VARCHAR(length=255), nullable=True),
    sa.Column('required_integrations', sqlite.JSON(), nullable=True),
    sa.Column('interactivity', sqlite.JSON(), nullable=True),
    sa.Column('user_access', sqlite.JSON(), nullable=True),
    sa.Column('customization', sqlite.JSON(), nullable=True),
    sa.Column('engagement_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('support_plan', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('delivery_model', sqlite.JSON(), nullable=True),
    sa.Column('budget_range', sa.VARCHAR(length=100), nullable=True),
    sa.Column('competitor_comparison', sa.TEXT(), nullable=True),
    sa.Column('roi_expectations', sa.TEXT(), nullable=True),
    sa.Column('tiered_pricing', sqlite.JSON(), nullable=True),
    sa.Column('analyst_notes', sa.TEXT(), nullable=True),
    sa.Column('suggested_pricing_model', sa.TEXT(), nullable=True),
    sa.Column('risk_factors', sa.TEXT(), nullable=True),
    sa.Column('next_steps', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_business_analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('company_website', sa.VARCHAR(length=255), nullable=True),
    sa.Column('use_case_description', sa.TEXT(), nullable=True),
    sa.Column('reference_links', sqlite.JSON(), nullable=True),
    sa.Column('attachments', sqlite.JSON(), nullable=True),
    sa.Column('verticals', sqlite.JSON(), nullable=True),
    sa.Column('custom_vertical', sa.VARCHAR(length=100), nullable=True),
    sa.Column('demo_details', sqlite.JSON(), nullable=True),
    sa.Column('client_suggestions', sa.TEXT(), nullable=True),
    sa.Column('problem_statement', sa.TEXT(), nullable=True),
    sa.Column('case_description', sa.TEXT(), nullable=True),
    sa.Column('stakeholders', sa.TEXT(), nullable=True),
    sa.Column('visualization_goal', sa.TEXT(), nullable=True),
    sa.Column('resources_provided', sa.TEXT(), nullable=True),
    sa.Column('documentation_status', sa.TEXT(), nullable=True),
    sa.Column('support_team_available', sa.BOOLEAN(), nullable=True),
    sa.Column('mathematical_modeling', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('analyst_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('client_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('industry_sector', sa.VARCHAR(length=100), nullable=True),
    sa.Column('company_size', sa.INTEGER(), nullable=True),
    sa.Column('annual_revenue', sa.FLOAT(), nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('has_bi_team', sa.BOOLEAN(), nullable=True),
    sa.Column('wants_bi_tool', sa.BOOLEAN(), nullable=True),
    sa.Column('will_provide_bi_projects', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('base_price', sa.FLOAT(), nullable=True),
    sa.Column('widgets_price', sa.FLOAT(), nullable=True),
    sa.Column('data_sources_price', sa.FLOAT(), nullable=True),
    sa.Column('integrations_price', sa.FLOAT(), nullable=True),
    sa.Column('features_price', sa.FLOAT(), nullable=True),
    sa.Column('branding_price', sa.FLOAT(), nullable=True),
    sa.Column('support_price', sa.FLOAT(), nullable=True),
    sa.Column('hosting_price', sa.FLOAT(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
