"""Create client table

Revision ID: f017a79f1c16
Revises: 
Create Date: 2025-05-27 22:02:15.365262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f017a79f1c16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyst_name', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('industry_sector', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Float(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('has_bi_team', sa.Boolean(), nullable=True),
    sa.Column('wants_bi_tool', sa.Boolean(), nullable=True),
    sa.Column('will_provide_bi_projects', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_objective', sa.Text(), nullable=True),
    sa.Column('expected_deliverables', sa.JSON(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('data_volume', sa.String(length=50), nullable=True),
    sa.Column('api_details', sa.JSON(), nullable=True),
    sa.Column('google_spreadsheet', sa.String(length=255), nullable=True),
    sa.Column('required_integrations', sa.JSON(), nullable=True),
    sa.Column('interactivity', sa.JSON(), nullable=True),
    sa.Column('user_access', sa.JSON(), nullable=True),
    sa.Column('customization', sa.JSON(), nullable=True),
    sa.Column('engagement_type', sa.String(length=50), nullable=True),
    sa.Column('support_plan', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('delivery_model', sa.JSON(), nullable=True),
    sa.Column('budget_range', sa.String(length=100), nullable=True),
    sa.Column('competitor_comparison', sa.Text(), nullable=True),
    sa.Column('roi_expectations', sa.Text(), nullable=True),
    sa.Column('tiered_pricing', sa.JSON(), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('suggested_pricing_model', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_business_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('use_case_description', sa.Text(), nullable=True),
    sa.Column('reference_links', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('verticals', sa.JSON(), nullable=True),
    sa.Column('custom_vertical', sa.String(length=100), nullable=True),
    sa.Column('demo_details', sa.JSON(), nullable=True),
    sa.Column('client_suggestions', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('case_description', sa.Text(), nullable=True),
    sa.Column('stakeholders', sa.Text(), nullable=True),
    sa.Column('visualization_goal', sa.Text(), nullable=True),
    sa.Column('resources_provided', sa.Text(), nullable=True),
    sa.Column('documentation_status', sa.Text(), nullable=True),
    sa.Column('support_team_available', sa.Boolean(), nullable=True),
    sa.Column('mathematical_modeling', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('filetype', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kanban_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('widgets_price', sa.Float(), nullable=True),
    sa.Column('data_sources_price', sa.Float(), nullable=True),
    sa.Column('integrations_price', sa.Float(), nullable=True),
    sa.Column('features_price', sa.Float(), nullable=True),
    sa.Column('branding_price', sa.Float(), nullable=True),
    sa.Column('support_price', sa.Float(), nullable=True),
    sa.Column('hosting_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    op.drop_table('kanban_ticket')
    op.drop_table('document')
    op.drop_table('demo_business_analysis')
    op.drop_table('project')
    op.drop_table('client')
    # ### end Alembic commands ###
